# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
jobs:
    - job: 'tests_and_checks'

      pool:
          vmImage: 'ubuntu-16.04'

      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '10.15.3'
            displayName: use node 10.15.3

          - script: yarn install --frozen-lockfile
            displayName: yarn install

          - script: yarn test -- --ci
            displayName: yarn test

            task: PublishTestResults@2
            inputs:
                testResultsFiles: $(System.DefaultWorkingDirectory)/test-results/junit.xml
                testRunTitle: axe-webdriverjs-sarif
            condition: always()
            displayName: publish test results

          - task: PublishCodeCoverageResults@1
            inputs:
                codeCoverageTool: Cobertura
                summaryFileLocation: $(System.DefaultWorkingDirectory)/test-results/coverage/cobertura-coverage.xml
                failIfCoverageEmpty: true
            displayName: publish code coverage

          - task: PublishBuildArtifacts@1
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/test-results/test_result.sarif'
                artifactName: 'CodeAnalysisLogs'
            condition: always()
            displayName: publish sarif results
